### ISSUE TITLE
CSS selector's scope

### ISSUE THREAD

**Issue by mudrd8mz** [vidyamantra/moodle-mod_virtualclass#4]
The CSS rule

    .text-center{
        text-align:left;
    }

can eventually affect all HTML nodes in Moodle using that class even if
they are out of your plugin scope. Please check
https://docs.moodle.org/dev/Plugin_contribution_checklist for the CSS
selectors section.

**Comment by bogatisuman** [comment]
Thank you for raising the issue, We have fixed this problem, we will close the issue after update latest version in moodle.

**Comment by bogatisuman** [comment]
Now we have updated on moodle.
